[package]
name = "rust"
version = "0.1.0"
edition = "2021"
description = "get sqld test data"


[dependencies]
egui = "0.27.2"
eframe = "0.27.2"
reqwest = { version = "0.12", features =["blocking"] }
serde = "1.0"
serde_json = "1.0"

[package.metadata.bundle]
identifier = "org.alphaorderly.sqld"
